In [15]:
import numpy as np

In [16]:
A = np.array([1,2,3,4])

In [17]:
np.ndim(A)

1

In [18]:
A.shape

(4,)

In [19]:
A.shape[0]

4

In [20]:
B = np.array([[1,2],[3,4],[5,6]])

In [21]:
np.ndim(B)

2

In [23]:
B.shape

(3, 2)

In [24]:
A = np.array([[1,2],[3,4]])

In [25]:
B = np.array([[5,6],[7,8]])

In [26]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [27]:
A = np.array([[1,2,3],[4,5,6]])

In [28]:
B = np.array([[1,2],[3,4],[5,6]])

In [29]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [32]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([7,8])

In [33]:
np.dot(A,B)

array([23, 53, 83])